django_todos/django_todos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TodolistView.as_view(),name='home'),
    path('todos/',include('todos.urls',namespace='todos')),
    
]
urlpatterns+=staticfiles_urlpatterns()

django_todos/todos/urls.py
from django.urls import path
from .views import *

app_name = 'todos'

urlpatterns = [
    path('add/',TodoCreateView.as_view(),name='add'),
    path('completed/',TodoCompletedView.as_view(),name='completed'),
    path('edit/<int:pk>/',TodoUpdateView.as_view(),name='edit'),
    path('detail/<int:pk>/',TodoDetailView.as_view(),name='detail'),
    path('delete/<int:pk>/',TodoDeleteView.as_view(),name='delete'),
    path('change_status/<int:pk>/',TodoStatusView.as_view(),name='status'),
    path('signup/',RegisterView.as_view(),name='signup'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',logoutView.as_view(),name='logout')
    
]

django_todos/todos/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

statuses = (
    ('NOT DONE','NOT DONE'),
    ('DONE','DONE'),

)

# Create your models here.
class Todo(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return self.name

class Status(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    todo = models.ForeignKey(Todo,on_delete=models.CASCADE)
    status = models.CharField(max_length=255,
                            choices=statuses,default='NOT DONE')
    changed_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.todo.name

django_todos/todos/forms.py
from django.forms import ModelForm, modelformset_factory
from .models import *

class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['name','description']

TodoFormSet = modelformset_factory(
    Todo, form=TodoForm, extra=1
)

django_todos/django_todos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from todos.models import Todo




class TodolistView(ListView):
    model = Todo
    template_name = 'index.html'

django_todos/todos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic import RedirectView, UpdateView, DeleteView
from django.views.generic.edit import CreateView, FormView
from django.views.generic.detail import DetailView
from django.contrib.auth.forms import (UserCreationForm, AuthenticationForm)
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import *
from .models import *



# Create your views here.
class TodoCreateView(LoginRequiredMixin,CreateView):
    model = Todo
    template_name = 'todos/add_todo.html'
    success_url = reverse_lazy('home')
    fields = ('name','description')

    
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        Status.objects.create(user=self.request.user,
                              todo=instance)
        return super().form_valid(form)

class TodoDetailView(DetailView):
    model = Todo
    template_name = 'todos/todo_detail.html'
    context_object = 'todo'

class TodoUpdateView(UpdateView):
    model = Todo
    template_name = 'todos/edit_todo.html'
    success_url = reverse_lazy('home')
    fields = ('name','description')

class TodoDeleteView(DeleteView):
    model = Todo
    success_url = reverse_lazy('home')

class TodoStatusView(RedirectView):
    url = reverse_lazy('home')

    def get(self,request, *args, **kwargs):
        todo_id = self.kwargs.get('pk')
        Status.objects.filter(todo=todo_id).update(status='DONE')
        return super().get(request,*args, **kwargs)

class TodoCompletedView(ListView):
    model = Todo
    template_name = 'index.html'

    def get_queryset(self):
        result = Todo.objects.exclude(status__status='DONE')
        if result:
            return result
        else:
            return Todo.objects.all()


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('todos:login')

class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'login.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)

class logoutView(RedirectView):
    url = reverse_lazy('home')

    def get(self,request, *args, **kwargs):
        logout(request)
        return super().get(request,*args, **kwargs)

    

django_todos/templates/index.html
{% extends 'layout.html' %}
{% block title %}list of todos {% endblock %}
{% block content %}


<h1>List of Todos</h1>
<div class='text-left'>
<a href='{% url 'todos:completed' %}' class='btn btn-default btn-lg'>Hide Completed Tasks</a>
</div>
<br>
{% if not object_list %}
    <p>There are no todos</p>
{% else %}
<table class="table">
    <tr>
        <th>Name</th>
        <th>Created On</th> 
        <th>Status</th>
        <th></th>
        <th></th>
        <th></th>
        
    </tr>
    {% for todo in object_list %}
    <tr class='text-left'>
        <td><a href='{% url 'todos:detail' pk=todo.pk %}'>{{todo.name}}</a></td>
        <td>{{todo.created_at}}</td>
        {{todo.status_set.status}}
        {% for task in todo.status_set.all %}
            {% if task.status == 'NOT DONE' %}
                <td>{{task.status}}</td>
                {% if user.is_authenticated %}
                    <td><a href='{% url 'todos:status' pk=todo.id %}'>CHANGE STATUS</a></td>
                {% endif %}
            {% else %}
                <td>{{task.status}}</td>
                <td>CLOSED BY: {{task.user}}</td>
            {% endif %}
        {% endfor %}
        {% if user == todo.user%}
            <td><a href='{% url 'todos:edit' pk=todo.id %}'>EDIT</a></td>
            <td><a href='{% url 'todos:delete' pk=todo.id %}'>DELETE</a></td>
        {% else %}
            <td></td>
            <td></td>
        {% endif%}
    </tr>
    {% endfor %}
</table>

{% endif %}


{% endblock %}

django_todos/templates/layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>todos | {% block title%}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">TODOS</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'home' %}">HOME</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'todos:add' %}">ADD</a></li>
            <li><a href="{% url 'todos:logout' %}">LOGOUT</a></li>
            {% else %}
            <li><a href="{% url 'todos:login'%}">LOGIN</a></li>
            <li><a href="{% url 'todos:signup'%}">SIGNUP</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
          {% block content %}


          {% endblock %}
        
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

django_todos/templates/login.html
{% extends 'layout.html' %}
{% load bootstrap %}

{% block title %}Add a todo {% endblock %}
{% block content%}
<form role="form" method='POST' action='' class='text-left'>
        <legend>Login below</legend>
        {% csrf_token %}
        {{ form|bootstrap }}
        <div class="form-group text-left">
          <button type="submit" class="btn btn-default btn-lg">Login</button>
          <a href="{% url 'todos:signup' %}" class="btn btn-default btn-lg">Signup</a>
        </div>
    </form>
{% endblock %}

django_todos/templates/signup.html
{% extends 'layout.html' %}
{% load bootstrap %}

{% block title %}Signup {% endblock %}
{% block content%}
<form role="form" method='POST' action='' class='text-left'>
        <legend>Create a account below</legend>
        {% csrf_token %}
        {{ form|bootstrap }}
        <div class="form-group text-left">
          <button type="submit" class="btn btn-default btn-lg">Signup</button>

        </div>
 </form>
{% endblock %}

django_todos/todos/templates/todos/add_todo.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block title %} Add Todo {% endblock %}
{% block content %}
<form method='POST' action='' class='text-left'>
    {% csrf_token%}
    {{form|bootstrap}}
    <input class='btn btn-default btn-lrg' type='submit' value='add a new todo'>
</form>
{% endblock %}

django_todos/todos/templates/todos/edit_todo.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block title %} Edit Todo {% endblock %}
{% block content %}
<form method='POST' action='' class='text-left'>
    {% csrf_token%}
    {{form|bootstrap}}
    <input class='btn btn-default btn-lrg' type='submit' value='Save'>
</form>
{% endblock %}

django_todos/todos/templates/todos/todo_confirm_delete.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block title %} Todo detail {% endblock %}
{% block content %}
<div class='jumbotron'>
    <form action="" method="post">{% csrf_token %}
        <h3>Are you sure you want to delete "{{ object }}"?</h3>
        <hr>
        <input class='btn btn-default btn-lg' type="submit" value="Confirm" />
    </form>
</div>


{% endblock %}

django_todos/todos/templates/todos/todo_detail.html
{% extends 'layout.html' %}
{% block title %}{{todo.name}}| Deatil{% endblock %}
{% block content %}
<div class='text-left'>
    <h2>Name</h2>
    <p>{{todo.name}}</p>
    <h2>Description</h2>
    <p>{{ todo.description|escape }}</p>
    <h2>created by</h2> 
    <p>{{todo.user}}</p>
    <h2>created on</h2>
    <p>{{ todo.created_at }}</p>
</div>
{% endblock%}